// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOyQCGPRr5ztkSl6YIS_SRWxKYQHHrsGA',
    appId: '1:1040428211318:android:eb4543ad675f1e32aad357',
    messagingSenderId: '1040428211318',
    projectId: 'salt-media-app1',
    storageBucket: 'salt-media-app1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5bO_PBDTC8K672RPuXQR9PmUGZoJguYU',
    appId: '1:1040428211318:ios:acc225a6f1c5c4d1aad357',
    messagingSenderId: '1040428211318',
    projectId: 'salt-media-app1',
    storageBucket: 'salt-media-app1.appspot.com',
    androidClientId: '1040428211318-5nvdmvataurtcoqspis3ov1t00g35moc.apps.googleusercontent.com',
    iosClientId: '1040428211318-3h0a53scbb0dre79uif6c7e96fhlidkf.apps.googleusercontent.com',
    iosBundleId: 'tv.stationcast.stationCast',
  );
}
